### ISSUE TITLE
AirMode Check box Feature

### ISSUE THREAD

**Issue by MS52390** [fedorcomander/kissfc-chrome-gui#1]
An AirMode enable/disable check box function in a future release of the GUI would be very useful. 

AirMode perimeters refresher:

If Min Command < Min Throttle ==> AirMode Enabled.
If Min Command = 1000 and arm = AUX switch ==> AirMode enabled.

**Comment by antstorm** [comment]
👍

Do you think it's possible to assign AirMode to a AUX switch? That would make landing so much smoother

**Comment by fedorcomander** [comment]
Never had issues with that. Just disarm (i use idle up now, but its the same) BEFORE touching the ground ;)))

**Comment by deepimpactio** [comment]
Couldn't you disarm with your switch?

**Comment by antstorm** [comment]
@deepimpactio yes, but that means dropping it, which by no means is a smooth landing :)

@fedorcomander I was under the impression that Idle Up and Air Mode are quite different, especially in terms of PID handling (at least in BetaFlight)

**Comment by fedorcomander** [comment]
This airmode fuzz introduced so many limitations... I term winding, bounce landings.. Oh my.
Its aint betaflight ;) airmode IS auto idle up in kissfc ;)

You can use separate idle-up and arm switches... Problem solved. :)

**Comment by antstorm** [comment]
@fedorcomander oh cool, didn't know that. Thanks for the tip, I'll try the idle up switch instead.

**Comment by antstorm** [comment]
Also hope there was a real airmode in KissFC…

**Comment by fedorcomander** [comment]
lol. call it way u want it. ;)

---
Cheers,
Alex

**Comment by antstorm** [comment]
I mean with real airmode you should be getting more upside down hang time comparing to idle up

**Comment by fedorcomander** [comment]
it hangs just fine

**Comment by antstorm** [comment]
I know, you just get slightly less hang time than on BetaFlight, compared two on the same quad

**Comment by fedorcomander** [comment]
Chad seems dont have any issues. and he uses idle up.

**Comment by andymac4182** [comment]
Not sure how airmode affects hang time @antstorm. Physics defines how long you can get hang time. If you have set your FC up right you will get the same on both :)

**Comment by antstorm** [comment]
@andymac4182 well, since in KISS FC airmode is just an idle up, your props spin faster when inverted at zero throttle, pulling you down more. Like you've said — physics.

Betaflight airmode is quite different. I wasn't aiming for a rant, love how KISS FC flies and just want to make it even better.

**Comment by fedorcomander** [comment]
airmode. idleup. all the same. 

---
Cheers,
Alex

**Comment by antstorm** [comment]
Not in betaflight, hence all the confusion. Would have been much clearer if it was called "idle up" in KISS.
