### ISSUE TITLE
Rates tab 3D model is too slow compared to the rotational speed it is supposed to represent with 24 fps refresh rate

### ISSUE THREAD

**Issue by lblblb** [fedorcomander/kissfc-chrome-gui#11]
I noticed for a while that the rates tool in the GUI is too slow compared to my quad when it's in the air. Today I measured it by setting it to 360°/s or 1 revolution per second and letting it spin around the roll axis for 60 s. It only completed 23 rolls in that time, with the stick at full deflection during the whole minute. This means that the rates tool 3D mode shows approx only 0.4 revolutions per second, while it should be 1.

![2016-08-26 11_51_33-kissfc](https://cloud.githubusercontent.com/assets/12690798/18001760/c09b20f6-6b84-11e6-9665-24bcd2688b53.png)

**Comment by fedorcomander** [comment]
Just checked... 59 turns in 60 seconds. my be i missed one. 

https://youtu.be/o9bkQrofO3c

Your turn ;)

**Comment by lblblb** [comment]
Huh, so for some reason it is just slower on my PC. I don't have any other issues with graphics and I just reinstalled the GUI. Any ideas?

https://youtu.be/bAMIhfBz04Y

**Comment by lblblb** [comment]
I solved it by setting my monitor to 60 fps mode, before it was 24 fps. So somehow you are relying on the screen refresh rate to make the 3D model spin?

**Comment by fedorcomander** [comment]
I do at the moment.

**Comment by lblblb** [comment]
Is there a better way, to prevent such issues?

**Comment by fedorcomander** [comment]
probably. I need to calculate time between frames - not frequency of the refresh rate. I will check. So far u are first to complain :)))

**Comment by lblblb** [comment]
OK, thanks!

**Comment by fedorcomander** [comment]
I changed calculations to be time based in place of screen refresh based. Can you test please?

**Comment by lblblb** [comment]
So what happens now is, in 60 fps it looks perfect, but in 24 fps it now is really choppy movement, with 360°/s the model gets rendered 6 times every revolution, but the speed it rotates is now correct as well. Before it was smooth in 24 fps mode, but just slow.

**Comment by lblblb** [comment]
By the way, if I stay the only one who noticed this, then you don't really need to spend too much time on this. I now know the issue and will stay with 60 fps anyway.

**Comment by fedorcomander** [comment]
thats ok. closing. 

---
Cheers,
Alex
