### ISSUE TITLE
android gui 1.14 can't work

### ISSUE THREAD

**Issue by ljlzonda** [fedorcomander/kissfc-chrome-gui#14]
In order to tune my quad outside without carrying my heavy laptop, I installed the 1.14 android gui to my phone(I'm running Dshot setup). But there is one big problem, the Mode of ESC will be auto set to PWM after saving the changes by the phone. So I still have to carry my laptop. Could you please fix that bug?

**Comment by hubertott** [comment]
Can I ask how you are installing a Chrome Desktop Extension on your Android phone?

**Comment by fedorcomander** [comment]
ljlzonda: wait till 1.1 firmware release. it works with 1.14 android app.
hubertott: you need to install APK file on android phone, not chrome extension.

**Comment by deepimpactio** [comment]
http://kiss.flyduino.net/download/kiss-fc-android-app-v1-02/

**Comment by ljlzonda** [comment]
@hubertott the apk for android!

**Comment by ljlzonda** [comment]
@deepimpactio this version don't support the RC30 firmware! Only the latest 1.14 Gui support.

**Comment by ljlzonda** [comment]
@fedorcomander when will the 1.1 firmware release?

**Comment by hubertott** [comment]
@fedorcomander all good I was mainly confused about the OP.

Glad to hear some stable releases are on the horizon ;)
