### ISSUE TITLE
Navigations buttons don’t work

### ISSUE THREAD

**Issue by iioel** [fedorcomander/kissfc-chrome-gui#17]
Hey, there is an issue when you run the web-app on linux. Navigation buttons do nothing wen the app is connected to my kissfc, I can't switch tabs so I get stuck on startup page.

Note : It was working in previous versions

Thanks, 

Yoël

**Comment by fedorcomander** [comment]
I never tried it on linux.

**Comment by derpixeldan** [comment]
It seems that it isn't connected properly. I'm not sure yet if it's a bug or validation behaves like this in general but I had the same issue before. Try addressing the right port to connect to.

**Comment by fedorcomander** [comment]
Whats in chrome console?

**Comment by iioel** [comment]
I don't have my quad for the moment, I will push the log as soon as I can

**Comment by derpixeldan** [comment]
Console will just say for example `Connection opened with ID: 76, Baud: 115200` but there's actually nothing physically connected to that port. I think there needs to be additional information when the FC wasn't successfully identified and navigation + connect button still need to be disabled. The actual failure response is missing.

**Comment by fedorcomander** [comment]
well.. sort the port first. may be RW permissions or something? owner? group?

**Comment by iioel** [comment]
I found the solution, for those who have the same problem, just uninstall the "modemmanager" package. He tried to create a modem with serial port, but he can't so he just block the serial port (I just looked in /var/log/syslog) and the app can't access to it.

**Comment by fedorcomander** [comment]
Very good. You can post your findings on RCG thread. Thanks for solving it. 
Alex.

**Comment by iioel** [comment]
Posted !
https://www.rcgroups.com/forums/showthread.php?2848997-Chrome-KissFC-wep-app-on-Linux
