### ISSUE TITLE
Q: Min version?

### ISSUE THREAD

**Issue by antstorm** [fedorcomander/kissfc-chrome-gui#19]
Hey Fedor,

It seems that `MIN_CONFIG_VERSION` was pushed to `108`, which seems to be higher than the available one (I've got `106` and as far as I remember it's the latest one publicly available). So what's the policy it?

Btw, keep up the good work!

**Comment by fedorcomander** [comment]
Its master, for FW 1.2.... Last publicly available FW should use 1.14...

**Comment by antstorm** [comment]
Which is a bit unfriendly towards OSS contributors, don't you think? :)

**Comment by fedorcomander** [comment]
So far there was none ;)))

**Comment by antstorm** [comment]
Got a package from you, thanks! :) Btw, how flyable is it? All the KISS FCs I've got are on the working quads, none lying on the bench :)

**Comment by fedorcomander** [comment]
Should be ok. But test without props first :)

**Comment by antstorm** [comment]
Got it, thanks!
