### ISSUE TITLE
FC FW Version Feature

### ISSUE THREAD

**Issue by MS52390** [fedorcomander/kissfc-chrome-gui#2]
Provide the FC's FW version via the KISS GUI. Perhaps right under the FC ver.

**Comment by fedorcomander** [comment]
The FW doesn't support it.

**Comment by dschafer77** [comment]
Can you discuss with Felix to implement this variable for future?

**Comment by gotnull** [comment]
Even if it's something as simple as a variable that holds the name of the file that was used for flashing.

**Comment by fedorcomander** [comment]
Its implemented now.

**Comment by fedorcomander** [comment]
![screen shot 2016-08-15 at 08 19 46](https://cloud.githubusercontent.com/assets/2101514/17657133/2b521c96-62c1-11e6-8400-10738b6b8cea.png)

**Comment by gotnull** [comment]
Brilliant, thanks.
