### ISSUE TITLE
Clear PID values Feature

### ISSUE THREAD

**Issue by MS52390** [fedorcomander/kissfc-chrome-gui#3]
A "Clear PIDS" button...perhaps next to the Share button in the PID category. 

Function: Set all PID values to 0, for use with testing. Upon button click, display a dialog box warning: "Are you sure you want to clear all PID values? This should only be used for testing" YES/Cancel buttons to exit dialog box.

**Comment by fedorcomander** [comment]
There is shared preset available from flyduino with zero pids ;)

**Comment by fedorcomander** [comment]
Added ZERO PIDS preset in 1.0.9
