### ISSUE TITLE
Motor tab

### ISSUE THREAD

**Issue by gregorg** [fedorcomander/kissfc-chrome-gui#4]
Add the motor tab like in cleanflight, to be able to check motors one by one. Don't know if the FC is able to let you do it... ;)

**Comment by fedorcomander** [comment]
At the moment there is no command available in the FW for motor control.

**Comment by fahrvergnuugen** [comment]
+1 would help with ESC calibration for non KISS ESCs.

**Comment by dschafer77** [comment]
+1 Very handy for trouble shooting

**Comment by fedorcomander** [comment]
Fixed RC28+
