### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by neuhausj** [fedorcomander/kissfc-chrome-gui#40]
Hello,
I have a problem with the latest version from this release (1.15.6).
As soon as I connect, I have the following error:
```
Error in event handler for serial.onReceive: RangeError: Offset is outside the bounds of the DataView
    at Object.kissProtocol.processPacket (chrome-extension://lpaialnijbomaabkpcebkkpbimpcmmgo/js/protocol.js:446:36)
    at Object.kissProtocol.read (chrome-extension://lpaialnijbomaabkpcebkkpbimpcmmgo/js/protocol.js:91:30)
    at chrome-extension://lpaialnijbomaabkpcebkkpbimpcmmgo/js/connection_handler.js:102:30
```

I can't do anything but disconnect. 

I am using the latest version of the firmware (1.1RC6) and the version 1.14 is working fine (except I Aux Functions will not saved its settings > can't use a switch to arm)

It looks like the code from protocol.js has changed and this line have problem:
`                obj.NFCF[1] = data.getUint16(144, 0);`

Thanks for your help!

**Comment by fedorcomander** [comment]
This version can work ONLY with 1.2 FW

**Comment by neuhausj** [comment]
Thank you for your answer. 
I understand why it was not working now.
