### ISSUE TITLE
LIMIT RC RATE/RATES COMBINATION TO BE SAVED

### ISSUE THREAD

**Issue by dschafer77** [fedorcomander/kissfc-chrome-gui#5]
Do not allow a user to save RC Rate/Rates combinations that will cause problems.
It would also be good to fix firmware so the FC deals better with this problem, ie when you hit something and rate exceeds 2000deg/sec same problem occurs.

**Comment by fedorcomander** [comment]
Is this still an issue with latest firmwares? It will spin like crazy but will stop when you release the sticks.
