### ISSUE TITLE
Can't setup the kiss FC

### ISSUE THREAD

**Issue by kenette73** [fedorcomander/kissfc-chrome-gui#50]
Hello, i flash my kiss to the new firmware 1.2 but i can't setup it with the gui 1.15.6 or 1.15.8 or 1.16.2.
I connect it but i can't switch to the other item.
Thanks Kevin

**Comment by fedorcomander** [comment]
u cant use 1.16 gui for sure. Its for 1.3 (next version)... Please download 1.15.6 gui from release page and try again.

**Comment by neuhausj** [comment]
Would it be possible to add a warning when the version is not correct? (FC too old / GUI not up to date)
This would be really helpful instead of being able to connect to FC but have a non working interface.

Ideally, the correct version needed from GUI should be pointed out (or a link to do a firmware upgrade).
Thanks !

**Comment by fedorcomander** [comment]
Its already there, actually.

**Comment by vetterfl** [comment]
same issue here. Board is connected but it stays on the 'welcome' page. Clicking any buttons doesn't do anything. the inspector says 'Switching content to configuration' and so on but that's it.
I've tried several configurations between firmware 1.1, 1.2, 1.3 and chrome GUI 1.15.6, 1.15.8 and 1.16.4.
I even tried an actual standalone in a windows vm. I'm using Linux mint 18.1 actually. Chromium version is 58.0.3029.110.
Any ideas?

**Comment by fedorcomander** [comment]
Try latest 1.3RC10 from rcgroups thread. It has all related artefacts included. Also i posted latest standalone guis there.

**Comment by gotnull** [comment]
Alex,

Can we assume that 1.3 (and the newer KISS24A firmware) introduced only changes to support SmartAudio on RX3 and no changes to flight characteristics?

The reason I ask is that 1.2 runs so well with KISS24A firmware prior to this release.

**Comment by fedorcomander** [comment]
No we cant. There was changes in flight characteristics. Its kinda offtopic here, please move questions to RCG thread.
