### ISSUE TITLE
ESC tab doesn't show Firmware version of ESC's anymore

### ISSUE THREAD

**Issue by derpixeldan** [fedorcomander/kissfc-chrome-gui#54]
When battery is connected of course:
![screen shot 2017-06-02 at 17 23 46](https://cloud.githubusercontent.com/assets/3369400/26732557/49106b70-47b8-11e7-90d8-567b8a336d3e.png)

**Comment by fedorcomander** [comment]
did u update esc to newest version? felix added more response data there. Well, ot worked for me for both versions btw.

**Comment by derpixeldan** [comment]
Tried it with two builds and it didn't work, tried it on another notebook where it worked, so I assume it was a local issue.
