### ISSUE TITLE
KISS CC motor order and FC rotation

### ISSUE THREAD

**Issue by Szzz** [fedorcomander/kissfc-chrome-gui#55]
Hi,
I don't know anything about programming, but I like to build quads.
I wanted to rotate the KISS CC in my quad, but there's an issue in my opinion: the motor pads stays the same and with a KISS FC it's ok, but with this kind of board you should be able to rotate the board and change with that the motor order. It's my own idea and don't know if anyone has requested something like this.
Great work guys.

**Comment by fedorcomander** [comment]
Its called motor output remapping, and its not supported by FW.
