### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by astewygriffin** [fedorcomander/kissfc-chrome-gui#56]
I'm unable to connect to Kiss Compact Ctrl when updated to version 1.3rc25 and GUI 1.16.14.  Tried on windows 7 x64 and windows 10 x64.  Also tried GUI 1.16.13, no luck.

**Comment by fedorcomander** [comment]
Strange. Show me.

**Comment by fedorcomander** [comment]
With FC in the frame ;)

**Comment by astewygriffin** [comment]
Hey, thanks for getting back to me.  Hope this works.
https://youtu.be/Phneri12x7E
I've checked my windows driver, which is the problem I had with 1.3rc10 and
it appears to be working correctly.
Cheers
Alan
