### ISSUE TITLE
MAC Flashing

### ISSUE THREAD

**Issue by s700ky** [fedorcomander/kissfc-chrome-gui#57]
Connects ok in BL mode, downloads online hex, on flashing removes protection then get

FAILURE: Failed to detect chip flash info, resultCode: 1

**Comment by fedorcomander** [comment]
Hold boot mode button UNTIL percents start ticking…

**Comment by s700ky** [comment]
Alex

You are amazing. Worked like a charm, and a reply in less than a minute.

God bless you buddy.

Paul

**Comment by svoland** [comment]
using iflight kiss fc. same problem but now is stuck in DFU and don't connects to gui (it did ).
same code 1 error
