### ISSUE TITLE
Disable trackpad scroll for field values

### ISSUE THREAD

**Issue by fahrvergnuugen** [fedorcomander/kissfc-chrome-gui#6]
If you place the cursor in a field and scroll with the trackpad the field values change. I'm assuming a mouse wheel will do the same - I'm using a Macbook Pro multitouch trackpad.

This might seem innocent but it's really easy to accidentally change a field value by mistake. Example: if you are trying to scroll a window and you don't realize that the cursor is in a field of the kissFC app, you will change the value to either a really high or really low number without realizing it.

I just did this by mistake, my P value went from 4.2 to 0.01. I got out to the field and wondered why my quad was uncontrollable!

An alternative to disabling the trackpad might be to highlight changed fields in red, but I really don't know why anyone would want to scroll the values in a field instead of typing them in.

**Comment by fedorcomander** [comment]
Done
