### ISSUE TITLE
Fc not arming

### ISSUE THREAD

**Issue by chloepita** [fedorcomander/kissfc-chrome-gui#61]
Im using a Spectrum radio Dx8 G2 and when i upgrade the duf file FC on to my kiss FC V1.03
it will not see the radio or arm. The weird thing is if i use the CC duf file it will arm but does
not fly it just does flips on the ground.

**Comment by fedorcomander** [comment]
And how is this related to the gui?

**Comment by chloepita** [comment]
I think its the Firmware not sure thats why im asking. I just started having this problem
when i upgraded to v1.3RC25. Ive updated the esc's to v1.11 and ive updated the new steele
pdb. When i do this the gui does not see the radio. The CC duf file will but this is a Kiss FC V1.03
and it should have the FC duf file. Hopfully that makes sence

**Comment by chloepita** [comment]
Im using the new Stand alone GUI v1.16.14

**Comment by gotnull** [comment]
I'd say if it's working with the CC firmware but not working for the FC firmware then that might not be a GUI issue. Over to you @fedorcomander

**Comment by fedorcomander** [comment]
not a gui issue.
