### ISSUE TITLE
Kiss FC V2 flash failed !!!! Can't connect for now :/

### ISSUE THREAD

**Issue by Barbaryann** [fedorcomander/kissfc-chrome-gui#66]
Hello,
The flash failed i don't know why. 
And now i can't connect and flash again.
I can i do t ?
I am on OS X.
Thanks
Yann

**Comment by fedorcomander** [comment]
connect usb
push reset button
connect gui
you will have flasher
flash again

**Comment by Barbaryann** [comment]
It works ! Thanks

**Comment by fedorcomander** [comment]
No problem. Enjoy.

**Comment by BlackBird11** [comment]
> connect usb
> push reset button
> connect gui
> you will have flasher
> flash again

thank you! worked like a charm!
