### ISSUE TITLE
Testing Linux Version

### ISSUE THREAD

**Issue by wangel** [fedorcomander/kissfc-chrome-gui#67]
This is on Ubuntu 17.10

Had to add my user to the "Dialout" group before being able to access the Serial Port,  Commands I used:

id -Gn <username>   to make sure I wasn't in the group
sudo usermod -a -G dialout <username>    this adds me to the group.  Note you have to logout and back for the change to take effect.  You can verify you are in the group with the "id" command again.

After adding myself to the group, I was able to access the serial port, however clicking Configuration, Data, Esc Flasher etc did nothing, just the same splash screen.   Also got these messages:

nwjs popup screen:  Your preferences can not be read.  Some features may be unavailable and changes to preferences won't be saved.

Running ./Kiss-Gui from the terminal also generated this "warning"

ERROR:desktop_window_tree_host_x11.cc(908)] Not implemented reched in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)

Thanks for the work Alex!!

**Comment by fedorcomander** [comment]
Can this help?

https://github.com/nwjs/nw.js/issues/5691 <https://github.com/nwjs/nw.js/issues/5691>

**Comment by fedorcomander** [comment]
permissions propblem is a permissions of the user data dir problem. doesnt affect anything and can be solved by changing permissions or --user-data-dir=/tmp/  for example. Why it doesnt connect, thats yet to be found. I see kiss sends 0x30 and get echoed back 0x30 instead of data. I am looking into that.

**Comment by fedorcomander** [comment]
Ok. Works.
What needed.
# Stop modem manager
sudo systemctl stop ModemService.service
# Add your user to dialout group
sudo usermod -a -G dialout YOUR_USER
# Delete (if you have) ~/.config/KISS GUI

<img width="1183" alt="screen shot 2018-02-04 at 17 10 28" src="https://user-images.githubusercontent.com/2101514/35779513-7a7fa396-09ce-11e8-89dd-b23eceb30d54.png">

**Comment by fedorcomander** [comment]
<img width="1130" alt="screen shot 2018-02-08 at 10 39 22" src="https://user-images.githubusercontent.com/2101514/35968137-467a9496-0cc3-11e8-8e1f-3589e54f9445.png">

**Comment by wangel** [comment]
Yes, sorry, wanted to follow up.  It is working 100% for me now too =)

Thanks :D

**Comment by fedorcomander** [comment]
Enjoy.
