### ISSUE TITLE
Motor Test Tool disconnects FC

### ISSUE THREAD

**Issue by JewsOfHazard** [fedorcomander/kissfc-chrome-gui#7]
When I click "TEST" everything becomes unclickable and the Gyro readings freeze.

**Comment by JewsOfHazard** [comment]
Nevermind, it isn't a bug per say. If the Firmware on the FC is not updated to 1.02 or above it does what I said above. If not it works fine.

**Comment by fedorcomander** [comment]
Yap. It works on RC28+ firmwares indeed.

**Comment by gotnull** [comment]
@fedorcomander Is there a way to determine which firmware is flashed on the FC?

**Comment by fedorcomander** [comment]
I've disabled motor test for 1.00 and 1.01 firmwares... U can try dev version. Full version of the FC will be available from RC29.

**Comment by JewsOfHazard** [comment]
Could you make a "transmitter-less" testing mode where all you have to do to spin up a motor would be to click and drag the throttle bar up or down?

**Comment by fedorcomander** [comment]
No. For safety reasons we have decided to do motor test this way and its not gonna change.

**Comment by JewsOfHazard** [comment]
That's totally fine, good to know you have thought of it.
